language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install Pillow coveralls
script:
    setup.py test
    coverage run --source=setup.py test
after_success:
    coveralls
