language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
addons:
    apt:
        packages:
            - ghostscript
install:
    - pip install Pillow coveralls
script:
    - python setup.py test
    - coverage run --source=zplgrf setup.py test
after_success:
    coveralls
notifications:
    email: false
